import React, { useEffect, useMemo, useState } from 'react';
import { Chess } from 'chess.js';
import Chessboard from './Chessboard.jsx';
import metadata from './data/openings-meta.json';
const PAGE_SIZE=24;
const normalize=value=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
export default function OpeningLibrary({ coords=true }) {
  const [catalog,setCatalog]=useState(null),[loadError,setLoadError]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{let active=true;setLoadError('');fetch(`${import.meta.env.BASE_URL}openings/catalog.json`).then(r=>{if(!r.ok)throw new Error('Could not load the opening library.');return r.json();}).then(data=>{if(active)setCatalog(data);}).catch(e=>{if(active)setLoadError(e.message);});return()=>{active=false;};},[retry]);
  const dataset=catalog || metadata;
  const uniqueNames=metadata.names;
  const indexed=useMemo(()=>(catalog?.openings || []).map(opening=>({...opening,search:normalize(`${opening.name} ${opening.eco} ${opening.pgn}`),compact:opening.pgn.replace(/\s/g,'').toLowerCase()})),[catalog]);
  const [query,setQuery]=useState(''),[volume,setVolume]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState(null),[ply,setPly]=useState(0),[flipped,setFlipped]=useState(false);
  const matches=useMemo(()=>{const q=normalize(query.trim());return indexed.filter(o=>(!volume || o.eco.startsWith(volume)) && (!q || o.search.includes(q) || o.compact.includes(q.replace(/\s/g,''))));},[query,volume,indexed]);
  const replay=useMemo(()=>{if(!selected)return null;const game=new Chess();game.loadPgn(selected.pgn);const moves=game.history({verbose:true});const board=new Chess();const positions=[board.fen()];for(const move of moves){board.move(move.san);positions.push(board.fen());}return {moves,positions};},[selected]);
  const pages=Math.max(1,Math.ceil(matches.length/PAGE_SIZE));
  const moveLabel=(i,move)=>`${Math.floor(i/2)+1}${i%2 ? '…' : '.'} ${move.san}`;
  const open=opening=>{setSelected(opening);setPly(0);setFlipped(false);};
  if(!catalog)return <div className="opening-empty"><p role="status">{loadError || 'Loading the opening library…'}</p>{loadError && <button onClick={()=>setRetry(n=>n+1)}>Try again</button>}</div>;
  if(selected && replay){const previous=replay.moves[ply-1];return <div className="opening-detail"><section className="opening-board-panel"><button className="opening-back" onClick={()=>setSelected(null)}>← All openings</button><span className="play-eyebrow">ECO {selected.eco}</span><h1>{selected.name}</h1><div className="play-board-frame"><Chessboard fen={replay.positions[ply]} orientation={flipped ? 'black' : 'white'} interactive={false} coords={coords} marks={previous ? {[previous.from]:'last',[previous.to]:'last'} : {}}/></div></section><aside className="opening-replay"><section className="play-card"><span className="play-eyebrow">EXPLORE THE LINE</span><h2>{ply ? `After ${moveLabel(ply-1,previous)}` : 'Starting position'}</h2><p className="opening-description">Step through the moves to see how this opening takes shape.</p><div className="opening-replay-controls"><button aria-label="First position" disabled={!ply} onClick={()=>setPly(0)}>⏮</button><button aria-label="Previous move" disabled={!ply} onClick={()=>setPly(p=>p-1)}>←</button><button aria-label="Next move" disabled={ply===replay.moves.length} onClick={()=>setPly(p=>p+1)}>→</button><button aria-label="Final position" disabled={ply===replay.moves.length} onClick={()=>setPly(replay.moves.length)}>⏭</button></div><p className="opening-step" role="status">Move {ply} of {replay.moves.length}</p><button className="opening-flip" onClick={()=>setFlipped(f=>!f)}>⇅ Flip board</button></section><section className="play-card"><h2>Opening moves</h2><div className="opening-moves">{replay.moves.map((move,i)=><button key={i} aria-pressed={ply===i+1} onClick={()=>setPly(i+1)}>{moveLabel(i,move)}</button>)}</div></section></aside></div>;}
  return <section className="opening-library"><div className="opening-library-heading"><div><span className="play-eyebrow">THE OPENING LIBRARY</span><h1>Find your next opening.</h1><p>{dataset.count.toLocaleString()} opening lines. {uniqueNames.toLocaleString()} distinct names. All five ECO volumes.</p></div></div><div className="opening-search"><label htmlFor="opening-search">Search by name, ECO code, or moves</label><div><input id="opening-search" type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Try Najdorf, C42, or 1. e4 e5"/>{query && <button onClick={()=>{setQuery('');setPage(0);}}>Clear</button>}</div></div><div className="opening-filters" aria-label="Filter ECO volume">{['','A','B','C','D','E'].map(v=><button key={v} aria-pressed={volume===v} onClick={()=>{setVolume(v);setPage(0);}}>{v ? `ECO ${v}` : 'All openings'}</button>)}<span role="status">{matches.length.toLocaleString()} lines</span></div><div className="opening-results">{matches.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE).map(o=><button className="opening-result" key={o.id} onClick={()=>open(o)}><div><span className="opening-eco">{o.eco}</span><strong>{o.name}</strong><span className="opening-arrow">↗</span></div><p>{o.pgn}</p><small>Explore the moves →</small></button>)}</div>{!matches.length && <div className="opening-empty"><h2>No openings found</h2><p>Try a broader name or clear the ECO filter.</p><button onClick={()=>{setQuery('');setVolume('');setPage(0);}}>Reset search</button></div>}<nav className="opening-pagination" aria-label="Opening results pages"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>← Previous</button><span>Page {page+1} of {pages}</span><button disabled={page>=pages-1} onClick={()=>setPage(p=>p+1)}>Next →</button></nav></section>;
}
